import type { WaveKind } from "./presets";
import { NEXT_DRUM_BANK } from "./nextDrumBank";

/** Explicit tuning, decay, metal/noise texture and body for every kit. */
export interface DrumCharacter {
  pitch: number;
  length: number;
  grain: number;
  body: WaveKind;
  metal: WaveKind;
  bright: number;
}

export const ADDITIONAL_DRUM_KITS = [
  ["kit-warehouse", "WAREHOUSE"],
  ["kit-tapeclub", "TAPE CLUB"],
  ["kit-digital", "DIGITAL SNAP"],
  ["kit-rattle", "RATTLE BOX"],
  ["kit-roundhouse", "ROUND HOUSE"],
  ["kit-wire", "WIRE ROOM"],
  ["kit-circuit", "CIRCUIT BREAK"],
  ["kit-velvet", "VELVET ROOM"],
  ["kit-copper", "COPPER HITS"],
  ["kit-subway", "SUBWAY"],
  ["kit-carbon", "CARBON PUNCH"],
  ["kit-neon", "NEON DRIVE"],
  ["kit-sand", "SAND ROOM"],
  ["kit-hollow", "HOLLOW BODY"],
  ["kit-spark", "SPARK KIT"],
  ["kit-rust", "RUST MACHINE"],
  ["kit-bamboo", "BAMBOO ROOM"],
  ["kit-ceramic", "CERAMIC HITS"],
  ["kit-vacuum", "VACUUM STEP"],
  ["kit-orbit", "ORBIT ROOM"],
] as const;

export const NEXT_DRUM_KITS = NEXT_DRUM_BANK.map(
  ({ id, name }) => [id, name] as const,
);

const ADDITIONAL_CHARACTERS: Readonly<Record<string, DrumCharacter>> = {
  "kit-warehouse": {
    pitch: 0.84,
    length: 1.38,
    grain: 12,
    body: "saw",
    metal: "reed",
    bright: 0.69,
  },
  "kit-tapeclub": {
    pitch: 0.68,
    length: 0.94,
    grain: 14,
    body: "triangle",
    metal: "mallet",
    bright: 0.31,
  },
  "kit-digital": {
    pitch: 1.38,
    length: 0.44,
    grain: 16,
    body: "pulse",
    metal: "organ",
    bright: 0.19,
  },
  "kit-rattle": {
    pitch: 1.16,
    length: 0.67,
    grain: 17,
    body: "reed",
    metal: "bell",
    bright: 0.77,
  },
  "kit-roundhouse": {
    pitch: 0.61,
    length: 1.26,
    grain: 19,
    body: "sine",
    metal: "mallet",
    bright: 0.23,
  },
  "kit-wire": {
    pitch: 1.47,
    length: 1.08,
    grain: 20,
    body: "brass",
    metal: "pluck",
    bright: 0.83,
  },
  "kit-circuit": {
    pitch: 1.26,
    length: 0.57,
    grain: 22,
    body: "pulse",
    metal: "bell",
    bright: 0.39,
  },
  "kit-velvet": {
    pitch: 0.74,
    length: 1.48,
    grain: 23,
    body: "sine",
    metal: "reed",
    bright: 0.17,
  },
  "kit-copper": {
    pitch: 1.58,
    length: 1.14,
    grain: 25,
    body: "mallet",
    metal: "bell",
    bright: 0.91,
  },
  "kit-subway": {
    pitch: 0.56,
    length: 1.93,
    grain: 26,
    body: "triangle",
    metal: "organ",
    bright: 0.34,
  },
  "kit-carbon": {
    pitch: 1.09,
    length: 0.39,
    grain: 27,
    body: "brass",
    metal: "reed",
    bright: 0.86,
  },
  "kit-neon": {
    pitch: 1.42,
    length: 0.89,
    grain: 29,
    body: "saw",
    metal: "organ",
    bright: 0.63,
  },
  "kit-sand": {
    pitch: 0.92,
    length: 0.74,
    grain: 30,
    body: "triangle",
    metal: "pluck",
    bright: 0.27,
  },
  "kit-hollow": {
    pitch: 0.79,
    length: 1.64,
    grain: 31,
    body: "sine",
    metal: "mallet",
    bright: 0.43,
  },
  "kit-spark": {
    pitch: 1.72,
    length: 0.51,
    grain: 33,
    body: "pulse",
    metal: "bell",
    bright: 0.73,
  },
  "kit-rust": {
    pitch: 1.03,
    length: 1.32,
    grain: 34,
    body: "saw",
    metal: "reed",
    bright: 0.96,
  },
  "kit-bamboo": {
    pitch: 1.21,
    length: 0.63,
    grain: 36,
    body: "mallet",
    metal: "pluck",
    bright: 0.57,
  },
  "kit-ceramic": {
    pitch: 1.61,
    length: 0.98,
    grain: 37,
    body: "bell",
    metal: "mallet",
    bright: 0.67,
  },
  "kit-vacuum": {
    pitch: 0.66,
    length: 0.33,
    grain: 38,
    body: "sine",
    metal: "pulse",
    bright: 0.14,
  },
  "kit-orbit": {
    pitch: 1.34,
    length: 1.78,
    grain: 39,
    body: "reed",
    metal: "bell",
    bright: 0.49,
  },
};

export const DRUM_CHARACTERS: Readonly<Record<string, DrumCharacter>> = {
  ...Object.fromEntries(
    NEXT_DRUM_BANK.map(({ id, character }) => [id, character]),
  ),
  ...ADDITIONAL_CHARACTERS,
  "kit-default": {
    pitch: 1,
    length: 1,
    grain: 3,
    body: "triangle",
    metal: "pulse",
    bright: 0.25,
  },
  "kit-grit": {
    pitch: 0.82,
    length: 0.68,
    grain: 9,
    body: "saw",
    metal: "reed",
    bright: 0.88,
  },
  "kit-metal": {
    pitch: 1.45,
    length: 1.3,
    grain: 2,
    body: "brass",
    metal: "bell",
    bright: 0.94,
  },
  "kit-soft": {
    pitch: 0.72,
    length: 0.72,
    grain: 32,
    body: "sine",
    metal: "mallet",
    bright: 0.18,
  },
  "kit-dust": {
    pitch: 0.88,
    length: 0.85,
    grain: 24,
    body: "triangle",
    metal: "reed",
    bright: 0.32,
  },
  "kit-lab": {
    pitch: 1.28,
    length: 0.52,
    grain: 6,
    body: "pulse",
    metal: "organ",
    bright: 0.12,
  },
  "kit-technoir": {
    pitch: 0.95,
    length: 1.45,
    grain: 4,
    body: "saw",
    metal: "bell",
    bright: 0.72,
  },
  "kit-lofi": {
    pitch: 0.65,
    length: 1.12,
    grain: 41,
    body: "sine",
    metal: "pluck",
    bright: 0.36,
  },
  "kit-pop": {
    pitch: 1.12,
    length: 0.6,
    grain: 5,
    body: "brass",
    metal: "mallet",
    bright: 0.65,
  },
  "kit-trap": {
    pitch: 0.78,
    length: 1.7,
    grain: 1,
    body: "sine",
    metal: "pulse",
    bright: 0.08,
  },
  "kit-808": {
    pitch: 0.9,
    length: 1.6,
    grain: 7,
    body: "sine",
    metal: "bell",
    bright: 0.3,
  },
  "kit-acoustic": {
    pitch: 1.05,
    length: 1.05,
    grain: 13,
    body: "mallet",
    metal: "bell",
    bright: 0.52,
  },
  "kit-dusty": {
    pitch: 0.7,
    length: 0.92,
    grain: 35,
    body: "triangle",
    metal: "pluck",
    bright: 0.28,
  },
  "kit-punch": {
    pitch: 1.18,
    length: 0.48,
    grain: 8,
    body: "brass",
    metal: "mallet",
    bright: 0.82,
  },
  "kit-electro": {
    pitch: 1.32,
    length: 0.78,
    grain: 10,
    body: "pulse",
    metal: "organ",
    bright: 0.42,
  },
  "kit-deep": {
    pitch: 0.58,
    length: 1.85,
    grain: 18,
    body: "sine",
    metal: "reed",
    bright: 0.22,
  },
  "kit-industrial": {
    pitch: 1.52,
    length: 1.18,
    grain: 15,
    body: "saw",
    metal: "bell",
    bright: 0.98,
  },
  "kit-wood": {
    pitch: 1.08,
    length: 0.82,
    grain: 28,
    body: "mallet",
    metal: "pluck",
    bright: 0.48,
  },
  "kit-glass": {
    pitch: 1.65,
    length: 1.55,
    grain: 11,
    body: "bell",
    metal: "mallet",
    bright: 0.78,
  },
  "kit-minimal": {
    pitch: 1.22,
    length: 0.36,
    grain: 21,
    body: "sine",
    metal: "pulse",
    bright: 0.16,
  },
};
