import type { VoicePreset } from "./presets";

/** Locally synthesized instruments; no downloads or recorded-sample claims. */
function sound(
  id: string,
  name: string,
  wave: VoicePreset["wave"],
  octaveBase: number,
  duty: number,
  envelope: VoicePreset["envelope"],
  extra: Partial<VoicePreset> = {},
): VoicePreset {
  return {
    id,
    name,
    wave,
    duty,
    envelope,
    pitchRange: { octaveBase },
    noiseMix: 0,
    noiseMode: "long",
    noiseRate: 8,
    level: 0.65,
    seed: 8101,
    ...extra,
  };
}

export const EXPANDED_PRESETS: readonly VoicePreset[] = [
  sound("preset-bells-crystal", "CRYSTAL BELL", "bell", 5, 0.5, {
    attack: 0.002,
    decay: 1.2,
    sustain: 0.08,
    release: 1.5,
  }),
  sound("preset-bells-musicbox", "MUSIC BOX", "bell", 5, 0.01, {
    attack: 0.001,
    decay: 0.45,
    sustain: 0,
    release: 0.65,
  }),
  sound("preset-bells-church", "TOWER BELL", "bell", 3, 0.38, {
    attack: 0.006,
    decay: 2.4,
    sustain: 0.12,
    release: 2.8,
  }),
  sound("preset-bells-vibes", "VIBES", "bell", 4, 0.002, {
    attack: 0.008,
    decay: 0.8,
    sustain: 0.18,
    release: 0.9,
  }),
  sound("preset-brass-trumpet", "SYNTH TRUMPET", "brass", 4, 0.95, {
    attack: 0.045,
    decay: 0.15,
    sustain: 0.75,
    release: 0.14,
  }),
  sound("preset-brass-horn", "ROUND HORN", "brass", 3, 0.3, {
    attack: 0.13,
    decay: 0.3,
    sustain: 0.8,
    release: 0.35,
  }),
  sound(
    "preset-brass-section",
    "BRASS SECTION",
    "brass",
    3,
    0.72,
    { attack: 0.08, decay: 0.2, sustain: 0.65, release: 0.24 },
    { noiseMix: 0.025 },
  ),
  sound("preset-brass-staccato", "BRASS HIT", "brass", 4, 1, {
    attack: 0.012,
    decay: 0.22,
    sustain: 0,
    release: 0.12,
  }),
  sound(
    "preset-fx-riser",
    "NOISE RISER",
    "noise",
    4,
    0.5,
    { attack: 1.8, decay: 0.2, sustain: 0.85, release: 0.6 },
    { level: 0.24, noiseMix: 1, noiseRate: 2 },
  ),
  sound(
    "preset-fx-wind",
    "WIND BED",
    "noise",
    3,
    0.5,
    { attack: 0.8, decay: 0.6, sustain: 0.55, release: 1.6 },
    { level: 0.2, noiseMix: 1, noiseRate: 48 },
  ),
  sound(
    "preset-fx-laser",
    "LASER DROP",
    "pulse",
    5,
    0.125,
    { attack: 0.001, decay: 0.28, sustain: 0, release: 0.18 },
    { level: 0.4, pitchSweep: { endRatio: 0.15, seconds: 0.3 } },
  ),
  sound(
    "preset-fx-shimmer",
    "BELL SHIMMER",
    "bell",
    5,
    0.83,
    { attack: 0.45, decay: 1.4, sustain: 0.35, release: 2 },
    { noiseMix: 0.045, level: 0.45 },
  ),
  sound("preset-keys-reed", "REED ORGAN", "brass", 4, 0.16, {
    attack: 0.012,
    decay: 0.05,
    sustain: 0.92,
    release: 0.09,
  }),
  sound("preset-strings-dulcimer", "DULCIMER", "pluck", 4, 0.22, {
    attack: 0.001,
    decay: 0.6,
    sustain: 0.2,
    release: 0.7,
  }),
  sound("preset-strings-zither", "ZITHER", "pluck", 5, 0.45, {
    attack: 0.002,
    decay: 1.1,
    sustain: 0.3,
    release: 1.1,
  }),
  sound(
    "preset-pads-air",
    "AIR PAD",
    "triangle",
    4,
    0.5,
    { attack: 0.9, decay: 0.6, sustain: 0.7, release: 1.8 },
    { noiseMix: 0.15, noiseRate: 32, level: 0.45 },
  ),
];
